export default {
  root:[
    {
      key:'1',
      title:"首页",
      path:'/admin/home',
      icon:'home'
    },
    {
      key:'3',
      title:"热门话题",
      icon:'hot',
      children:[
        {
          key:'4-1',
          title:'热门列表',
          path:'/admin/hot/list'
        },
        {
          key:'4-2',
          title:'新建热门',
          path:'/admin/hot/add'
        }
      ]
    }
  ],
  admin:[
    {
      key:'1',
      title:"首页",
      path:'/admin/home',
      icon:'home'
    },
    {
      key:'3',
      title:"热门话题",
      path:'/admin/hot/list',
      icon:'hot'
    }
  ]
} 
